---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest
    notify: restart Apache
  - name: add index file to remote host
    copy: 
      src: /home/ubuntu/index.html 
      dest: /var/www/html 
      owner: apache 
      group: apache 
      mode: 0644

  handlers:
  - name: restart Apache
    service: name=apache2 state=restared